import { NgModule } from '@angular/core';
import { LayoutModule } from '@angular/cdk/layout';

import {
    MatButtonModule,
    MatInputModule,
    MatSidenavModule,
    MatListModule,
    MatMenuModule,
    MatIconModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatCardModule,
    MatDialogModule,
    MatTableModule,
    MatOptionModule,
    MatSelectModule,
    MatTabsModule,
    MatPaginatorModule,
    MatSortModule,
    MatGridListModule,
} from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatInputModule,
    MatSidenavModule,
    MatListModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatCheckboxModule,
    MatToolbarModule,
    LayoutModule,
    MatDialogModule,
    MatTableModule,
    MatOptionModule,
    MatSelectModule,
    MatTabsModule,
    MatPaginatorModule,
    MatSortModule,
    MatSelectModule,
    MatGridListModule
  ],
  declarations: [],
  exports: [
    MatButtonModule,
    MatInputModule,
    MatSidenavModule,
    MatListModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatCheckboxModule,
    MatToolbarModule,
    LayoutModule,
    MatTableModule,
    MatOptionModule,
    MatSelectModule,
    MatTabsModule,
    MatSortModule,
    MatDialogModule,
    MatSelectModule,
    MatPaginatorModule,
    MatGridListModule,
  ]
})
export class MaterialModule { }
